import { DEFAULT_SEED } from "../config/gameConfig";
import type { AdventureLevel, LevelSegment } from "./levelTypes";

const segments: LevelSegment[] = [
  {
    id: "station-intro",
    section: 1,
    type: "intro",
    length: 520,
    startX: 0,
    endX: 520,
    groundY: 650,
    visualTheme: "research_valley",
    next: ["valley-run"],
    camera: "follow",
    successCriterion: "NURI leaves the research station",
  },
  {
    id: "valley-run",
    section: 1,
    type: "run",
    length: 400,
    startX: 520,
    endX: 920,
    groundY: 650,
    visualTheme: "research_valley",
    next: ["gap-rose"],
    camera: "follow",
    successCriterion: "NURI reaches the first gap",
  },
  {
    id: "gap-rose",
    section: 1,
    type: "small_gap",
    length: 380,
    startX: 920,
    endX: 1300,
    groundY: 650,
    visualTheme: "neon_forest",
    obstacleType: "small_gap",
    requiredAction: "jump",
    requiredAmount: 1,
    checkpointAfter: true,
    next: ["slope-run"],
    camera: "anticipate",
    successCriterion: "NURI lands beyond the gap",
    waitX: 1010,
    landingX: 1170,
  },
  {
    id: "slope-run",
    section: 2,
    type: "run",
    length: 300,
    startX: 1300,
    endX: 1600,
    groundY: 630,
    visualTheme: "ruined_slope",
    next: ["high-ledge"],
    camera: "follow",
    successCriterion: "NURI reaches the steep ledge",
  },
  {
    id: "high-ledge",
    section: 2,
    type: "high_ledge",
    length: 520,
    startX: 1600,
    endX: 2120,
    groundY: 610,
    visualTheme: "ruined_slope",
    obstacleType: "high_ledge",
    requiredAction: "build_blocks",
    requiredAmount: 3,
    checkpointAfter: true,
    next: ["route-fork"],
    camera: "focus",
    successCriterion: "Three energy stones form a climbable stair",
    waitX: 1740,
    landingX: 1950,
  },
  {
    id: "route-fork",
    section: 3,
    type: "route_fork",
    length: 480,
    startX: 2120,
    endX: 2600,
    groundY: 550,
    visualTheme: "ruined_slope",
    obstacleType: "route_fork",
    next: ["route-left-gap", "route-right-bridge"],
    camera: "wide",
    successCriterion: "A ten second chat vote chooses the route",
    waitX: 2260,
    landingX: 2480,
  },
  {
    id: "route-left-gap",
    section: 3,
    type: "small_gap",
    length: 420,
    startX: 2600,
    endX: 3020,
    groundY: 530,
    visualTheme: "neon_forest",
    obstacleType: "small_gap",
    requiredAction: "jump",
    requiredAmount: 1,
    next: ["ravine-main"],
    camera: "anticipate",
    successCriterion: "NURI clears the risky upper gap",
    waitX: 2700,
    landingX: 2870,
  },
  {
    id: "route-right-bridge",
    section: 3,
    type: "broken_bridge",
    length: 520,
    startX: 2600,
    endX: 3120,
    groundY: 610,
    visualTheme: "ancient_ravine",
    obstacleType: "broken_bridge",
    requiredAction: "build_blocks",
    requiredAmount: 3,
    alternatives: [{ action: "build_bridge", amount: 1 }],
    next: ["ravine-main"],
    camera: "focus",
    successCriterion: "The safe route bridge is repaired",
    waitX: 2740,
    landingX: 2990,
  },
  {
    id: "ravine-main",
    section: 4,
    type: "ravine",
    length: 840,
    startX: 3120,
    endX: 3960,
    groundY: 610,
    visualTheme: "ancient_ravine",
    obstacleType: "ravine",
    requiredAction: "build_bridge",
    requiredAmount: 1,
    alternatives: [{ action: "build_blocks", amount: 6 }],
    checkpointAfter: true,
    next: ["summit-climb"],
    camera: "wide",
    successCriterion: "All six bridge segments are solid",
    waitX: 3280,
    landingX: 3770,
  },
  {
    id: "summit-climb",
    section: 5,
    type: "run",
    length: 520,
    startX: 3960,
    endX: 4480,
    groundY: 570,
    visualTheme: "beacon_summit",
    next: ["beacon-gate"],
    camera: "follow",
    successCriterion: "NURI reaches the summit gate",
  },
  {
    id: "beacon-gate",
    section: 5,
    type: "repair_gate",
    length: 500,
    startX: 4480,
    endX: 4980,
    groundY: 540,
    visualTheme: "beacon_summit",
    obstacleType: "repair_gate",
    requiredAction: "helper",
    requiredAmount: 1,
    next: ["beacon-finish"],
    camera: "focus",
    successCriterion: "The Corgi helper repairs and opens the gate",
    waitX: 4620,
    landingX: 4840,
  },
  {
    id: "beacon-finish",
    section: 5,
    type: "finish",
    length: 520,
    startX: 4980,
    endX: 5500,
    groundY: 520,
    visualTheme: "beacon_summit",
    next: [],
    camera: "wide",
    successCriterion: "NURI inserts the core and activates the sky beacon",
  },
];

export function createBeaconLevel(seed = DEFAULT_SEED): AdventureLevel {
  return {
    id: "path-to-sky-beacon",
    name: "DER WEG ZUM HIMMELSLEUCHTFEUER",
    version: "1.0.0",
    seed,
    startX: 120,
    finishX: 5360,
    segments: structuredClone(segments),
  };
}
